services:
  - type: web
    name: langchain-master-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: OPENAI_MODEL
        value: gpt-5-mini
      - key: OPENAI_API_KEY
        sync: false
      - key: LANGSMITH_TRACING
        value: "true"
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_PROJECT
        value: langchain-master
